# https://github.com/sympy/sympy/blob/master/.travis.yml
# https://github.com/codecov/example-python
# https://docs.travis-ci.com
# https://stackoverflow.com/a/3237883
# https://stackoverflow.com/a/5688592
# https://stackoverflow.com/a/6270803

language: python

before_install:
  - pip install --upgrade pip setuptools wheel
  - pip install pytest-cov codecov awscli

install:
  - pip install .

script:
  # for testing, limit downloads from the resource servers by using cached resources;
  # note that the master branch is tested weekly via `cron`, so this ensures all Python
  # versions will be periodically integration tested with the resource servers
  - set -e
  - NUM_JOBS=4
  - SELECTED_JOB=$((10#$(date +%V) % $NUM_JOBS))  # identify a job based on week of the year
  - DOWNLOADS_ENABLED=false
  - |
    if [[ $TRAVIS_PULL_REQUEST != "false" ]]; then
      # download resources for all jobs on a pull request
      DOWNLOADS_ENABLED=true
    elif [[ $TRAVIS_BRANCH == "master" && $SELECTED_JOB == $JOB_ID ]]; then
      # download resources for selected job on master branch
      DOWNLOADS_ENABLED=true
    fi
  - |
    if [[ $DOWNLOADS_ENABLED == "false" ]]; then
      # use cached resources on Amazon S3
      aws s3 cp s3://lineage-resources/resources.tar.gz resources.tar.gz
      if [[ -f resources.tar.gz ]]; then
        tar -xzf resources.tar.gz
        rm resources.tar.gz
      fi
    fi
  - pytest --cov=lineage tests
  - |
    if [[ $SELECTED_JOB == $JOB_ID ]]; then
      codecov
    fi

stages:
  - check formatting
  - test
  - name: deploy
    if: tag IS present

jobs:
  include:
    - stage: check formatting
      python: 3.6
      before_install:
        - pip install black==19.10b0
      script:
        - black --check --diff .
    - stage: test
      python: 3.5
      env: JOB_ID=0
    - python: 3.6
      env: JOB_ID=1
    - python: 3.7
      env: JOB_ID=2
    - python: 3.8
      env: JOB_ID=3
    - stage: deploy
      python: 3.6
      script: skip
      deploy:
        - provider: pypi
          user: "apriha"
          password:
            secure: "ILDxck7IPSffABa4mWFANETAOJgazxXJRJBFoMQ+0TKxsrTKVA6VDtrUBEAgxAdm2Zp9Lwh8vsOKodEToTrcm5J4JmnFsyz+pxBbPNpKE1RU4bn+X0qqd3D//iK6DoATxrQCS73MZA7GoMOEL7dvU2R8d2d8i6H3x4lDCIp3dcPRZm1+YYGo51bwv6MYJGcN9lQOtQlVgFYPp/9TSAiwK5sWjQk8Bfv7ASIJWGb0+oLW5AK468ANk1agof+pg56d041vWYDqTBuuaZs6gEYxJQSk0V0o896NoNoqenfIch39KeHnL4jTBUhftDk/NNT/wGfi8JasGC/ks+ESE7R8BwbWYb0QH9AhBQSraAjIr0IEyoOXYYl2FlghHWFC2/mBKZcmQXuL+Dx6tJxvAP914bB2sb+ZNNcBfuPkfzeOYoVosTly/O/MPoyuj2/Ohmw76hKzeGu2IE4UILQUsggaZvgVk/A+Vu8KmeOx15X+IgHn3ahJ3550K4d5vFTRlvY1EZQP5XY5Mx7OW55Orm71wZKOMIN4Y6COyZA7NCs0tCR5M7EjIk/j401Dm/O75hcYIY0J69eZiifSIXUNsJ+6QmOvhZJA8ZtYNlJ6nyGhBAF22a6wp7E2OQEY2WR2X1ZMRaP9SSr7X8wUbKHTt9JbEVFQwqTQzqdP+8Szj/Hh0nA="
          distributions: "sdist bdist_wheel"
          on:
            branch: master
            tags: true
